ERROR :2020-01-03 04:16:22,836 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :84 :139848052889344  :Thread-1 :6479 :error: name 'validate_email' is not defined while as email entered was not a vaild email address
ERROR :2020-01-03 04:18:02,892 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :84 :140217114711808  :Thread-1 :6510 :error: name 'validate_email' is not defined while as email entered was not a vaild email address
ERROR :2020-01-03 04:27:33,510 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :129 :139705434879744  :Thread-1 :6968 :error: name 'render_to_string' is not defined while loging in 
ERROR :2020-01-03 04:27:57,771 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :129 :139705434879744  :Thread-1 :6968 :error: name 'render_to_string' is not defined while loging in 
ERROR :2020-01-03 04:29:21,700 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :130 :140109195835136  :Thread-1 :7011 :error: name 'render_to_string' is not defined while loging in 
ERROR :2020-01-03 04:32:34,815 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :95 :140333123294976  :Thread-1 :7289 :email address is already registered  while logging in
ERROR :2020-01-03 04:33:38,110 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :130 :140333123294976  :Thread-1 :7289 :error: name 'render_to_string' is not defined while loging in 
ERROR :2020-01-03 04:35:27,981 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :130 :140603616618240  :Thread-3 :7389 :error: encode() got multiple values for argument 'algorithm' while loging in 
ERROR :2020-01-03 04:47:01,973 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :145 :140531082290944  :Thread-2 :8091 :error: name 'render_to_string' is not defined while loging in 
ERROR :2020-01-03 04:50:52,425 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :156 :139803522909952  :Thread-2 :8314 :error: name 'user' is not defined while loging in 
ERROR :2020-01-03 04:53:08,728 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :156 :140598829733632  :Thread-2 :8392 :error: name 'user' is not defined while loging in 
ERROR :2020-01-03 04:53:47,727 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :156 :139957734487808  :Thread-2 :8549 :error: Reverse for 'activate' with keyword arguments '{'uidb64': 'MTA', 'token': '5ct-8cf6365150e0cd9f8692'}' not found. 1 pattern(s) tried: ['activate\\/$'] while loging in 
ERROR :2020-01-03 04:55:39,128 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :156 :139848857466624  :Thread-4 :8643 :error: Reverse for 'activate' with keyword arguments '{'uidb64': 'MTE', 'token': '5ct-03adfb9b4c3ec7bee029'}' not found. 1 pattern(s) tried: ['activate\\/$'] while loging in 
ERROR :2020-01-03 04:57:30,418 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :157 :139809147696896  :Thread-2 :8729 :error: name 'user_created' is not defined while loging in 
ERROR :2020-01-03 04:58:23,071 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :158 :140543360214784  :Thread-2 :8810 :error: name 'user_created' is not defined while loging in 
ERROR :2020-01-03 04:59:13,978 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :158 :140575656986368  :Thread-2 :8863 :error: name 'user_created' is not defined while loging in 
ERROR :2020-01-03 05:09:35,240 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :158 :140575656986368  :Thread-4 :8863 :error: name 'user_created' is not defined while loging in 
ERROR :2020-01-03 05:20:03,204 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :161 :140564322014976  :Thread-2 :9852 :error: name 'user' is not defined while loging in 
ERROR :2020-01-03 05:21:42,359 :/home/user/Desktop/GitFolder/Fellowship/project/project/snippets/views.py :161 :139642003257088  :Thread-2 :10139 :error: name 'user' is not defined while loging in 
